### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [Livinglist/todo#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by gitforsuraj** [comment]
Hello Professor

**Comment by Sarfaraz-Mohammed** [comment]
Hey!

**Comment by senu-tecle** [comment]
Hi team! this is Senait

**Comment by ProfRojas** [comment]
Please have all of your teammates respond. Otherwise, you will only receive partial credit for the GitHub portion.

**Comment by Livinglist** [comment]
Section 5, Group 7

**Comment by ProfRojas** [comment]
Thanks!
